service1.internal, alt-service1.internal {
	import dev_certs

	reverse_proxy {
		to mitm

		header_up X-MITM-Emoji ":one:"
		header_up X-MITM-To "localhost:8080"

		header_up Host "localhost:8080"
	}
}
