# examples/getting-started/justfile

import '../.just/justfile'

# show available recipes
help:
    @just --list

up: _clear-project-containers _ensure-network (_ensure-certs "certs")
    docker compose up -d --wait --pull always --build --force-recreate

down:
    docker compose down

restart: down up

ps:
    docker compose ps

logs:
    docker compose logs -f

smoke: (_check-status "https://utils.citm.localhost" "200") (_check-status "https://whoami.localhost" "200")
