[program:mitmproxy]
directory=/mitm-scripts
; mitmweb log output is suppressed without a PTY under supervisord.
command=/usr/bin/script -q -c "/usr/local/bin/start-mitmproxy" /dev/null
autostart=true
autorestart=true
startretries=3
user=root

stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

stopsignal=TERM
