[program:proxylens-server]
directory=/proxy-lens/server
command=/usr/local/bin/start-proxylens-server
autostart=true
autorestart=true
startretries=3
user=root

stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

stopsignal=TERM
