[program:supervisor-webui]
directory=/supervisor/webui
command=uv run gunicorn -w 2 -b 0.0.0.0:5001 --enable-stdio-inheritance supervisor_webui.app:app
autostart=true
autorestart=true
startretries=3
user=root

stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

stopsignal=TERM
