app1.localhost {
	import dev_certs

	reverse_proxy {
		to mitm

		header_up X-MITM-Emoji ":one:"
		header_up X-MITM-To "app1.internal:443"
		header_up Host "app1.internal"

		transport http {
			tls
		}
	}
}

