*.citm.localhost {
	import dev_certs

	reverse_proxy {
		to "{labels.2}.citm.localhost:{$CADDY_ADMIN_PORT}"

		transport http {
			tls
			network_proxy none
		}
	}
}

*.citm.app1.localhost {
	import dev_certs

	reverse_proxy {
		to "app1.internal:{$CADDY_ADMIN_PORT}"
		header_up Host "{labels.3}.citm.localhost:{$CADDY_ADMIN_PORT}"

		transport http {
			tls
			tls_server_name citm.localhost
			network_proxy none
		}
	}
}

*.citm.app2.localhost {
	import dev_certs

	reverse_proxy {
		to "app2.internal:{$CADDY_ADMIN_PORT}"
		header_up Host "{labels.3}.citm.localhost:{$CADDY_ADMIN_PORT}"

		transport http {
			tls
			tls_server_name citm.localhost
			network_proxy none
		}
	}
}

*.citm.app3.localhost {
	import dev_certs

	reverse_proxy {
		to "app3.internal:{$CADDY_ADMIN_PORT}"
		header_up Host "{labels.3}.citm.localhost:{$CADDY_ADMIN_PORT}"

		transport http {
			tls
			tls_server_name citm.localhost
			network_proxy none
		}
	}
}

