# gateway citm
*.citm.localhost {
	import dev_certs

	reverse_proxy {
    # for example in mitm.citm.service1.localhost, labels.2 is mitm
		to "{labels.2}.citm.localhost:3858"

		transport http {
			tls
			network_proxy none
		}
	}
}

# services citm
*.citm.service1.localhost {
	import dev_certs

	reverse_proxy {
    # labels.1 is the service name (i.e., service1)
		to "{labels.1}.internal:3858"

    # for example in mitm.citm.service1.localhost, labels.3 is mitm
		header_up Host "{labels.3}.citm.localhost:3858"

		transport http {
			tls
			tls_server_name citm.localhost
			network_proxy none
		}
	}
}
