service2.localhost, alt-service2.localhost {
	import dev_certs

	reverse_proxy {
		to mitm

		header_up X-MITM-Emoji ":two:"
		header_up X-MITM-To "service2.internal:443"

		header_up Host "service2.internal"

		transport http {
			tls
		}
	}
}
