service1.localhost, alt-service1.localhost {
	# Enable on-demand TLS for this site configuration
	import dev_certs

	reverse_proxy {
		# This can be anything but localhost, so that the request goes through MITMProxy
		to mitm

		# Flow marker for MITMProxy to be able to distinguish flows easier
		header_up X-MITM-Emoji ":one:"
    # Route the request to the service via its internal DNS name
		header_up X-MITM-To "service1.internal:443"

		header_up Host "service1.internal"

		transport http {
			tls
		}
	}
}
