---
name: citm-development-container

services:
  cert-maker:
    build:
      context: ../shared-certificates
      dockerfile: Dockerfile
    volumes:
      - ../shared-certificates:/shared-certificates
    command:
      - /bin/bash
      - /shared-certificates/mk-devcerts.sh
  devcontainer:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        DEVCONTAINER: true
    depends_on:
      cert-maker:
        condition: service_completed_successfully
    volumes:
      - vscode-server-data:/home/dev/.vscode-server
      - ../shared-certificates/certs:/certs:ro
      - ../caddy/Caddyfile:/etc/caddy/Caddyfile
      - ..:/workspace:cached
    environment:
      - DOCKER_HOST=tcp://localhost:2375
      - CITM_NETWORK=citm-example
      - ENABLE_PROXYLENS_SERVER=true
      - CITM_DNS_UPSTREAM_NAMESERVERS=1.1.1.1

    ports:
      # BEGIN GENERATED EXPOSED PORTS
      - '0.0.0.0:${CADDY_ADMIN_PORT:-63858}:63858'
      - '0.0.0.0:${CADDY_HTTP_PORT:-80}:80'
      - '0.0.0.0:${CADDY_HTTPS_PORT:-443}:443/udp'
      - '0.0.0.0:${CADDY_HTTPS_PORT:-443}:443'
      - '0.0.0.0:${CITM_UTILS_WEB_PORT:-19000}:19000'
      - '0.0.0.0:${MITMPROXY_HTTP_PROXY_PORT:-19080}:19080'
      - '0.0.0.0:${MITMPROXY_SOCKS_PROXY_PORT:-19081}:19081'
      - '0.0.0.0:${MITMPROXY_WEB_PORT:-19082}:19082'
      - '0.0.0.0:${PROXYLENS_SERVER_PORT:-19003}:19003'
      - '0.0.0.0:${SUPERVISOR_WEBUI_PORT:-19001}:19001'
      # END GENERATED EXPOSED PORTS
    networks:
      - citm-example
    command: /start-supervisord
    init: true
    tty: true
  docker-socket-proxy:
    image: alpine/socat:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: service:devcontainer
    command:
      - TCP-LISTEN:2375,fork,reuseaddr
      - UNIX-CONNECT:/var/run/docker.sock

networks:
  citm-example:
    external: true

volumes:
  vscode-server-data:
    driver: local
