# examples/http-proxy-and-dns-forwarder/justfile

import '../.just/justfile'

# show available recipes
help:
    @just --list

up: _clear-project-containers _ensure-network (_ensure-certs "certs")
    docker compose up -d --wait --pull always --build --force-recreate

down:
    docker compose down

restart: down up

ps:
    docker compose ps

logs:
    docker compose logs -f

smoke:
    #!/usr/bin/env bash
    set -euo pipefail
    export http_proxy=http://127.0.0.1:8380
    export https_proxy=http://127.0.0.1:8380
    just _check-status "https://utils.citm.internal:3858" "200"
    just _check-status "http://whoami.internal" "200"
