site_name: Caddy in the Middle
docs_dir: src
site_url: https://fardjad.com/caddy-in-the-middle/

theme:
  name: material
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["../testcontainers/python"]

nav:
  - Home: index.md
  - Tutorials:
    - Getting Started: tutorials/getting-started.md
    - Gateway and Sidecars: tutorials/gateway-and-sidecars.md
  - How-To Guides:
    - Development Root CA Generation: how-to/create-dev-root-ca.md
