name: citm-examples-mocking

services:
  books-api:
    image: python:3
    volumes:
      - ./app:/app:ro
    networks:
      - my-citm-network
    command: python /app/books_app.py
    working_dir: /app
    labels:
      # Register this service in the CITM network
      - citm_network=my-citm-network
      - citm_dns_names=books.internal
  citm:
    build:
      context: ../..
      dockerfile: Dockerfile
    volumes:
      # Required for service discovery
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # A directory containing rootCA.pem and rootCA-key.pem
      - ./certs:/certs:ro
      # A directory containing Caddy config files
      - ./caddy-conf.d:/etc/caddy/conf.d:ro
      # A directory containing mock response templates
      - ./mocks:/citm-mocks:ro
    environment:
      # Discover services in this network
      - CITM_NETWORK=my-citm-network
      # Load all mock templates from the mounted mocks directory
      - MOCK_PATHS=/citm-mocks/**/*.mako
    ports:
      # Caddy ports
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'
      - '0.0.0.0:443:443/udp'
    networks:
      - my-citm-network

networks:
  my-citm-network:
    name: my-citm-network
    external: true
